### ISSUE TITLE
Cannot seem to launch pyrpl-windows-develop.exe?

### ISSUE THREAD

**Issue by ttuibk** [lneuhaus/pyrpl#346]
Windows 10.   Downloaded today.  Error message below.

Traceback (most recent call last):
  File "site-packages\pandas\__init__.py", line 26, in <module>
  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\pandas\_libs\__init__.py", line 4, in <module>
  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
  File "pandas/_libs/tslibs/conversion.pxd", line 11, in init pandas._libs.tslib
  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
ImportError: No module named 'pandas._libs.tslibs.np_datetime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyrpl\__main__.py", line 10, in <module>
  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "pyrpl\__init__.py", line 66, in <module>
  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "pyrpl\redpitaya.py", line 19, in <module>
  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "pyrpl\redpitaya_client.py", line 29, in <module>
  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "pyrpl\hardware_modules\__init__.py", line 23, in <module>
  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "pyrpl\hardware_modules\dsp.py", line 2, in <module>
  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "pyrpl\attributes.py", line 20, in <module>
  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "pyrpl\widgets\attribute_widgets.py", line 13, in <module>
  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "pyrpl\curvedb.py", line 31, in <module>
  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\pandas\__init__.py", line 35, in <module>
ImportError: C extension: No module named 'pandas._libs.tslibs.np_datetime' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyrpl\__main__.py", line 12, in <module>
ImportError: attempted relative import with no known parent package
[12512] Failed to execute script __main__

**Comment by ttuibk** [comment]
Ok sorry thanks.  I was just trying to check if differentiators were making it into the PID module or not.  I've tried "additional modules" in the lockbox module but cannot get it to work yet.
