### ISSUE TITLE
Failed when starting PyRPL in Windows 10 due to DLL loading failure

### ISSUE THREAD

**Issue by KaifengC** [lneuhaus/pyrpl#471]
Hi I'm trying to connect my  Redpitaya STEM-125-14 using PyRPL on a windows 10 mecmachines hine for the first time.
The Redpitaya is running `STEMlab_125-xx_OS_1.04-7_stable`, will connected and tested since I can access to it through my web browser and use it as an oscilloscope.

Then I download `pyrpl-windows.exe` following the manual and when the program scans over my LAN ports, I get the following error message:
```bash
0 D:\OneDrive\Small_Tools\RedPitaya\pyrpl-windows.exe
Calling Pyrpl(**{})
INFO:pyrpl:Please select or create a configuration file in the file selector window!
INFO:pyrpl:All your PyRPL settings will be saved to the config file
    C:/Users/Kaifeng/pyrpl_user_dir/config\global_config.yml
If you would like to restart PyRPL with these settings, type "pyrpl.exe global_config" in a windows terminal or
    from pyrpl import Pyrpl
    p = Pyrpl('global_config')
in a python terminal.
INFO:pyrpl.redpitaya:Please choose the hostname of your Red Pitaya in the hostname selector window!
['192.168.0.104']
ERROR:paramiko.transport:Unknown exception: DLL load failed: 找不到指定的模块。
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "site-packages\paramiko\transport.py", line 1890, in run
ERROR:paramiko.transport:  File "site-packages\paramiko\transport.py", line 1988, in _negotiate_keys
ERROR:paramiko.transport:  File "site-packages\paramiko\kex_ecdh_nist.py", line 32, in start_kex
ERROR:paramiko.transport:  File "site-packages\paramiko\kex_ecdh_nist.py", line 51, in _generate_key_pair
ERROR:paramiko.transport:  File "site-packages\cryptography\hazmat\backends\__init__.py", line 15, in default_backend
ERROR:paramiko.transport:  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
ERROR:paramiko.transport:  File "site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module>
ERROR:paramiko.transport:  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
ERROR:paramiko.transport:  File "site-packages\cryptography\hazmat\backends\openssl\backend.py", line 53, in <module>
ERROR:paramiko.transport:  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
ERROR:paramiko.transport:  File "site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 13, in <module>
ERROR:paramiko.transport:ImportError: DLL load failed: 找不到指定的模块。
ERROR:paramiko.transport:
```

My guess is that I lack some packages on my computer. Does anyone have any clone about how to solve this?

I tested this on two different window 10 machines and get the same error message.

**Comment by ruvilecamwasam** [comment]
I'm getting the same issue on Windows 11.

**Comment by RAILMEMS1** [comment]
I'm also getting this on Windows 11. Has anyone solved this?

**Comment by youngbaby777** [comment]
I'm also getting this on Windows 10. Has anyone solved this?

**Comment by youngbaby777** [comment]
I reinstalled my python environment using anaconda3 5.1.0 (python 3.6), and successed connecting the board.
