### ISSUE TITLE
bug in docker. 

### ISSUE THREAD

**Issue by karu2003** [lneuhaus/pyrpl#506]
your docker is not working. the package qt5-default no longer exists.

The last Debian was a buster.

in Python 3.11 i have  TypeError.

Traceback (most recent call last):
  File "/workspaces/redp_examples/pyrpl_acq.py", line 2, in <module>
    from pyrpl import RedPitaya
  File "/opt/conda/lib/python3.11/site-packages/pyrpl/__init__.py", line 59, in <module>
    global_config = MemoryTree('global_config', source='global_config')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pyrpl/memory.py", line 507, in __init__
    self._savetimer.setInterval(self._loadsavedeadtime*1000)
TypeError: setInterval(self, msec: int): argument 1 has unexpected type 'float'

**Comment by michaelcroquette** [comment]
Pyrpl is only compatible with python up to 3.9 for the moment.
