### ISSUE TITLE
paramiko.transport:ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by linhz0hz** [lneuhaus/pyrpl#510]
Hello,
When using the old windows version of pyrpl, I got this error message:
`ERROR:paramiko.transport:Unknown exception: DLL load failed: The specified module could not be found.
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "site-packages\paramiko\transport.py", line 1890, in run
ERROR:paramiko.transport:  File "site-packages\paramiko\transport.py", line 1988, in _negotiate_keys
ERROR:paramiko.transport:  File "site-packages\paramiko\kex_ecdh_nist.py", line 32, in start_kex
ERROR:paramiko.transport:  File "site-packages\paramiko\kex_ecdh_nist.py", line 51, in _generate_key_pair
ERROR:paramiko.transport:  File "site-packages\cryptography\hazmat\backends\__init__.py", line 15, in default_backend
ERROR:paramiko.transport:  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
ERROR:paramiko.transport:  File "site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module>
ERROR:paramiko.transport:  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
ERROR:paramiko.transport:  File "site-packages\cryptography\hazmat\backends\openssl\backend.py", line 53, in <module>
ERROR:paramiko.transport:  File "c:\projects\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
ERROR:paramiko.transport:  File "site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 13, in <module>
ERROR:paramiko.transport:ImportError: DLL load failed: The specified module could not be found.
ERROR:paramiko.transport:
Traceback (most recent call last):
  File "pyrpl\redpitaya.py", line 237, in start_ssh
  File "pyrpl\sshshell.py", line 53, in __init__
  File "site-packages\paramiko\client.py", line 331, in connect
  File "site-packages\paramiko\util.py", line 276, in retry_on_signal
  File "site-packages\paramiko\client.py", line 331, in <lambda>
socket.timeout: timed out

During handling of the above exception, another exception occurred:`

I believe this is related to this https://github.com/pyca/cryptography/issues/10388 , ultimately an old python version? I guess I have no control of the version as I am running a pre-packaged binary? I see that the pre-compiled windows binary is from 2017 on source-forge, maybe this should no longer be recommended program to use?

**Comment by Dylan-Danese** [comment]
Hey! We had the same problem error, but managed to bypass it by launching the binary from the cmd. I also cloned the python repo, updated the depreciated pyqtgraph class "GraphicsWindow" to "GraphicsLayoutWidget" in all of the widget files (https://pyqtgraph.readthedocs.io/en/pyqtgraph-0.11.1/graphicswindow.html) and managed to make it run for python 3.9, although not sure of the stability of this yet though, but the oscilloscope and sweep works. I'm by no means good at python but figured it might help people here.
